server:
  port: 88
  max-http-header-size: 8192
  compression:
    min-response-size: 512
    enabled: true
    mime-types: text/html,text/css,text/javascript,application/javascript,image/gif,image/png,image/jpg
logging:
  config: classpath:log4j2.xml
spring:
  velocity:
    cache: false
    charset: UTF-8
    view-names: error,index,projects,tags,tagView,archives,post,about,login,admin/blog_add,admin/project,
                admin/monitor,admin/blog_modify,admin/blog_list,admin/info,admin/result,admin/resume
    properties:
      input.encoding: UTF-8
      output.encoding: UTF-8
      velocimacro.library: VM_global_library.vm
      directive.parse.max.depth: 2
  http:
    encoding:
      charset: UTF-8
      force: false
    multipart:
      max-file-size: 3MB
      max-request-size: 10MB
  cache:
    cache-names: ehcache
    ehcache:
      config: ehcache.xml
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/fireyaoblog?useUnicode:true&amp;characterEncoding:UTF-8
    driverClassName: com.mysql.jdbc.Driver
#    schema: classpath:import.sql
#    data: classpath:data.sql
#    initialize: false
    sql-script-encoding: UTF-8
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 50
      minimum-idle: 5
mybatis:
  type-aliases-package: com.fireyao.blog.model,com.fireyao.blog.mapping
  type-handlers-package: org.apache.ibatis.type.LocalDateTypeHandler
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
pic:
  home:

